### ISSUE TITLE
Local environment setup / yarn install issues

### ISSUE THREAD

**Issue by samajammin** [ethereum/eth2.0-deposit#301]
### Problem

Hey folks - I'm trying to set this project up locally & having some classic install issues. Here's what happens when I try to install dependencies:

```
~/code/ef/forks/eth2.0-deposit « git:(intl)
$ yarn
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-animate-on-scroll@2.1.5" has unmet peer dependency "classnames@^2.2.5".
warning " > styled-components@5.0.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > tslint-plugin-prettier@2.3.0" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
[4/4] 🔨  Building fresh packages...
[1/16] ⠠ bcrypto
[2/16] ⠠ keccak
[3/16] ⠠ secp256k1
[4/16] ⠠ keccak
error /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/Library/Caches/node-gyp/12.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/samrichards/Library/Caches/node-gyp/12.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/samrichards/Library/Caches/node-gyp/12.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/samrichards/.nvm/versions/node/v12.19.1/bin/node" "/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3




warning Error running install script for optional dependency: "/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/Library/Caches/node-gyp/12.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/samrichards/Library/Caches/node-gyp/12.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/samrichards/Library/Caches/node-gyp/12.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command \"/Users/samrichards/.nvm/versions/node/v12.19.1/bin/node\" \"/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents
gyp ERR! node -v v12.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

Despite these errors, the project appears to run fine when running `yarn start`.

Where the problem persists is attempting to add new dependencies, e.g. I try running `yarn add react-intl`, I see similar failures & the project's package.json is not updated:

```

~/code/ef/forks/eth2.0-deposit « git:(intl)
$ yarn add react-intl
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-animate-on-scroll@2.1.5" has unmet peer dependency "classnames@^2.2.5".
warning " > styled-components@5.0.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > tslint-plugin-prettier@2.3.0" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
[4/4] 🔨  Building fresh packages...
[1/16] ⠈ bcrypto
[7/16] ⠈ fsevents
[3/16] ⠈ secp256k1
[6/16] ⠈ core-js
error /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/Library/Caches/node-gyp/12.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/samrichards/Library/Caches/node-gyp/12.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/samrichards/Library/Caches/node-gyp/12.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/samrichards/.nvm/versions/node/v12.19.1/bin/node" "/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/sha3




warning Error running install script for optional dependency: "/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/samrichards/Library/Caches/node-gyp/12.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/samrichards/Library/Caches/node-gyp/12.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/samrichards/Library/Caches/node-gyp/12.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command \"/Users/samrichards/.nvm/versions/node/v12.19.1/bin/node\" \"/Users/samrichards/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/samrichards/code/ef/forks/eth2.0-deposit/node_modules/fsevents
gyp ERR! node -v v12.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error


~/code/ef/forks/eth2.0-deposit « git:(intl)
$ gs
On branch intl
nothing to commit, working tree clean
```

### Solution

Any sense of how to solve this? I have Xcode installed (despite the errors claiming no Xcode detected). In the past I've been able to solve these kind of issue following this guide:
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
But no luck this time around 😕 

### Context

I'm running macOS Catalina v10.15.5, using node v12 via nvm:

```
~/code/ef/forks/eth2.0-deposit « git:(intl)
$ node --version
v12.19.1
```

I'm going to try updating my macOS to Big Sur & see if that helps. In the meantime, I'd appreciate any tips! Thanks.

**Comment by samajammin** [comment]
I tried uninstalling & re-installing Xcode... this time it worked 😄 
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
