### ISSUE TITLE
Can't open file 'src/deposit.py'

### ISSUE THREAD

**Issue by econoar** [ethereum/eth2.0-deposit#60]
After running the final command to generate keys:

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'src/deposit.py': [Errno 2] No such file or directory

**Comment by yslcrypto** [comment]
Yes, 
Looks like this [package reorg](https://github.com/ethereum/eth2.0-deposit-cli/commit/96200d76ae30b966d43e879f21d5d1b4d7455917) broke this. `src` has been renamed to `cli`, but running the command with `cli/deposity.py` instead of `src/deposit.py` gives a `ModuleNotFoundError: No module named 'eth2deposit'`

Quick fix: move `deposit.py` from `eth2.0-deposit-cli/cli/` to `eth2.0-deposit-cli/` and run `python3 deposit.py --num_validators 1` instead

**Comment by hwwhww** [comment]
Sorry for the wreck!!

Another quick fix:
```sh
git clone https://github.com/ethereum/eth2.0-deposit-cli.git
cd eth2.0-deposit-cli
pip3 install -r requirements.txt
python3 setup.py install
python3 cli/deposit.py --num_validators 1
```

I understand that it's weird to have both `requirements.txt` and `setup.py`. While we want to keep Python dependencies locked with `requirements.txt` and keep it simple, having a `setup.py` is easier for testing. The quick fix may be changed once we figure out a better solution.

**Comment by 2ge** [comment]
Hi guys, I got problem which is probably connected with this one (I really dont know from where comes pip8...but I guess thats not a problem here):
```
brano@Ubuntu-1604-xenial-64-minimal:~$ git clone https://github.com/ethereum/eth2.0-deposit-cli.git
Cloning into 'eth2.0-deposit-cli'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 871 (delta 3), reused 6 (delta 1), pack-reused 857
Receiving objects: 100% (871/871), 350.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (503/503), done.
Checking connectivity... done.
brano@Ubuntu-1604-xenial-64-minimal:~$ cd eth2.0-deposit-cli
brano@Ubuntu-1604-xenial-64-minimal:~/eth2.0-deposit-cli$ pip3 install -r requirements.txt
Collecting py-ecc==4.0.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/25/43/b2956cb42045ee000d301133289e7fbfb04ff0148c13cff2f8d81f1b4c11/py_ecc-4.0.0-py3-none-any.whl
Collecting pycryptodome==3.9.7 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/1b/79/f2a9bb60abd1ccd34006bab9a6ebbe03abe8c660366d20be390b85277fb1/pycryptodome-3.9.7-cp37-cp37m-manylinux1_x86_64.whl
Collecting click==7.0 (from -r requirements.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting ssz==0.2.3 (from -r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/9a/d3/6655d110e087977fbe487c11d5df3458ad2becd055cf665955ac63cf0d90/ssz-0.2.3-py3-none-any.whl
Collecting eth-typing==2.2.1 (from -r requirements.txt (line 41))
  Using cached https://files.pythonhosted.org/packages/bc/c4/c9c78597d0400e5bc1c3cdd031fdfa6629333a31591fcc5fa8519a7ea89c/eth_typing-2.2.1-py3-none-any.whl
Collecting eth-utils==1.8.4 (from -r requirements.txt (line 46))
  Using cached https://files.pythonhosted.org/packages/10/d4/5ffae25b2028338388f3647ca45142b45737d173e216739c55f9a3cd4b6d/eth_utils-1.8.4-py3-none-any.whl
Collecting mypy-extensions==0.4.3 (from -r requirements.txt (line 49))
  Using cached https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Collecting lru-dict==1.1.6 (from -r requirements.txt (line 52))
  Using cached https://files.pythonhosted.org/packages/00/a5/32ed6e10246cd341ca8cc205acea5d208e4053f48a4dced2b1b31d45ba3f/lru-dict-1.1.6.tar.gz
Collecting pyrsistent==0.15.7 (from -r requirements.txt (line 54))
  Using cached https://files.pythonhosted.org/packages/90/aa/cdcf7ef88cc0f831b6f14c8c57318824c9de9913fe8de38e46a98c069a35/pyrsistent-0.15.7.tar.gz
Collecting eth-hash==0.2.0 (from -r requirements.txt (line 56))
  Using cached https://files.pythonhosted.org/packages/0d/d8/0f0c8d4ccaa4c8d25524fd1ed9f5c6d9551b52b74b973f338de3f0a23111/eth_hash-0.2.0-py3-none-any.whl
Collecting cytoolz==0.10.1 (from -r requirements.txt (line 59))
  Using cached https://files.pythonhosted.org/packages/62/b1/7f16703fe4a497879b1b457adf1e472fad2d4f030477698b16d2febf38bb/cytoolz-0.10.1.tar.gz
Collecting toolz==0.10.0 (from -r requirements.txt (line 61))
  Using cached https://files.pythonhosted.org/packages/22/8e/037b9ba5c6a5739ef0dcde60578c64d49f45f64c5e5e886531bfbc39157f/toolz-0.10.0.tar.gz
Collecting six==1.14.0 (from -r requirements.txt (line 63))
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting cached-property==1.5.1 (from -r requirements.txt (line 66))
  Using cached https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Building wheels for collected packages: lru-dict, pyrsistent, cytoolz, toolz
  Running setup.py bdist_wheel for lru-dict ... done
  Stored in directory: /home/brano/.cache/pip/wheels/b7/ef/06/fbdd555907a7d438fb33e4c8675f771ff1cf41917284c51ebf
  Running setup.py bdist_wheel for pyrsistent ... done
  Stored in directory: /home/brano/.cache/pip/wheels/b5/78/ac/f26a78a989cd97f90981d96a560d7e1da5e1307284301d94e8
  Running setup.py bdist_wheel for cytoolz ... done
  Stored in directory: /home/brano/.cache/pip/wheels/64/2a/18/d962b614e055577e7d9a3e4813e0742f822ca9c8800cc3783a
  Running setup.py bdist_wheel for toolz ... done
  Stored in directory: /home/brano/.cache/pip/wheels/e1/8b/65/3294e5b727440250bda09e8c0153b7ba19d328f661605cb151
Successfully built lru-dict pyrsistent cytoolz toolz
Installing collected packages: mypy-extensions, toolz, cytoolz, eth-hash, eth-typing, eth-utils, cached-property, py-ecc, pycryptodome, click, lru-dict, six, pyrsistent, ssz
Successfully installed cached-property-1.5.1 click-7.0 cytoolz-0.10.1 eth-hash-0.2.0 eth-typing-2.2.1 eth-utils-1.8.4 lru-dict-1.1.6 mypy-extensions-0.4.3 py-ecc-4.0.0 pycryptodome-3.9.7 pyrsistent-0.15.7 six-1.14.0 ssz-0.2.3 toolz-0.10.0
You are using pip version 8.1.1, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
brano@Ubuntu-1604-xenial-64-minimal:~/eth2.0-deposit-cli$ python3 setup.py install
running install
running bdist_egg
running egg_info
creating eth2deposit.egg-info
writing eth2deposit.egg-info/PKG-INFO
writing dependency_links to eth2deposit.egg-info/dependency_links.txt
writing top-level names to eth2deposit.egg-info/top_level.txt
writing manifest file 'eth2deposit.egg-info/SOURCES.txt'
file eth2deposit.py (for module eth2deposit) not found
reading manifest file 'eth2deposit.egg-info/SOURCES.txt'
writing manifest file 'eth2deposit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file eth2deposit.py (for module eth2deposit) not found
creating build
creating build/lib
creating build/lib/eth2deposit
copying eth2deposit/credentials.py -> build/lib/eth2deposit
copying eth2deposit/deposit.py -> build/lib/eth2deposit
copying eth2deposit/settings.py -> build/lib/eth2deposit
copying eth2deposit/__init__.py -> build/lib/eth2deposit
creating build/lib/eth2deposit/utils
copying eth2deposit/utils/ascii_art.py -> build/lib/eth2deposit/utils
copying eth2deposit/utils/crypto.py -> build/lib/eth2deposit/utils
copying eth2deposit/utils/validation.py -> build/lib/eth2deposit/utils
copying eth2deposit/utils/ssz.py -> build/lib/eth2deposit/utils
copying eth2deposit/utils/constants.py -> build/lib/eth2deposit/utils
copying eth2deposit/utils/__init__.py -> build/lib/eth2deposit/utils
creating build/lib/eth2deposit/key_handling
copying eth2deposit/key_handling/keystore.py -> build/lib/eth2deposit/key_handling
copying eth2deposit/key_handling/__init__.py -> build/lib/eth2deposit/key_handling
creating build/lib/eth2deposit/key_handling/key_derivation
copying eth2deposit/key_handling/key_derivation/mnemonic.py -> build/lib/eth2deposit/key_handling/key_derivation
copying eth2deposit/key_handling/key_derivation/tree.py -> build/lib/eth2deposit/key_handling/key_derivation
copying eth2deposit/key_handling/key_derivation/path.py -> build/lib/eth2deposit/key_handling/key_derivation
copying eth2deposit/key_handling/key_derivation/__init__.py -> build/lib/eth2deposit/key_handling/key_derivation
creating build/lib/tests
creating build/lib/tests/test_key_handling
copying tests/test_key_handling/test_keystore.py -> build/lib/tests/test_key_handling
copying tests/test_key_handling/__init__.py -> build/lib/tests/test_key_handling
creating build/lib/tests/test_key_handling/test_key_derivation
copying tests/test_key_handling/test_key_derivation/test_path.py -> build/lib/tests/test_key_handling/test_key_derivation
copying tests/test_key_handling/test_key_derivation/test_mnemonic.py -> build/lib/tests/test_key_handling/test_key_derivation
copying tests/test_key_handling/test_key_derivation/test_tree.py -> build/lib/tests/test_key_handling/test_key_derivation
copying tests/test_key_handling/test_key_derivation/__init__.py -> build/lib/tests/test_key_handling/test_key_derivation
file eth2deposit.py (for module eth2deposit) not found
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/eth2deposit
copying build/lib/eth2deposit/credentials.py -> build/bdist.linux-x86_64/egg/eth2deposit
copying build/lib/eth2deposit/deposit.py -> build/bdist.linux-x86_64/egg/eth2deposit
copying build/lib/eth2deposit/settings.py -> build/bdist.linux-x86_64/egg/eth2deposit
creating build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/ascii_art.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/crypto.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/validation.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/ssz.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/constants.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
copying build/lib/eth2deposit/utils/__init__.py -> build/bdist.linux-x86_64/egg/eth2deposit/utils
creating build/bdist.linux-x86_64/egg/eth2deposit/key_handling
creating build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation
copying build/lib/eth2deposit/key_handling/key_derivation/mnemonic.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation
copying build/lib/eth2deposit/key_handling/key_derivation/tree.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation
copying build/lib/eth2deposit/key_handling/key_derivation/path.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation
copying build/lib/eth2deposit/key_handling/key_derivation/__init__.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation
copying build/lib/eth2deposit/key_handling/keystore.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling
copying build/lib/eth2deposit/key_handling/__init__.py -> build/bdist.linux-x86_64/egg/eth2deposit/key_handling
copying build/lib/eth2deposit/__init__.py -> build/bdist.linux-x86_64/egg/eth2deposit
creating build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/tests/test_key_handling
copying build/lib/tests/test_key_handling/test_keystore.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling
creating build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation
copying build/lib/tests/test_key_handling/test_key_derivation/test_path.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation
copying build/lib/tests/test_key_handling/test_key_derivation/test_mnemonic.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation
copying build/lib/tests/test_key_handling/test_key_derivation/test_tree.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation
copying build/lib/tests/test_key_handling/test_key_derivation/__init__.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation
copying build/lib/tests/test_key_handling/__init__.py -> build/bdist.linux-x86_64/egg/tests/test_key_handling
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/credentials.py to credentials.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/deposit.py to deposit.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/settings.py to settings.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/ascii_art.py to ascii_art.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/crypto.py to crypto.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/validation.py to validation.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/ssz.py to ssz.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/constants.py to constants.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/utils/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation/mnemonic.py to mnemonic.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation/tree.py to tree.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation/path.py to path.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/key_derivation/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/keystore.py to keystore.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/key_handling/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/eth2deposit/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/test_keystore.py to test_keystore.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation/test_path.py to test_path.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation/test_mnemonic.py to test_mnemonic.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation/test_tree.py to test_tree.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/test_key_derivation/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_key_handling/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying eth2deposit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eth2deposit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eth2deposit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eth2deposit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    python_requires=">=3.7,<4",
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```
